import setuptools
setuptools.setup(
    name='cdev',
    version='0.0',
    scripts=['./cdev/scripts/cdev', './core/scripts/cdev_core' ],
    author='CDEV LLC',
    description='CLI for cdev',
    packages=['cdev', 'core'],
    install_requires=[
        "boto3",
        "botocore",
        "certifi",
        "charset-normalizer",
        "colorama",
        "commonmark",
        "dataclasses",
        "decorator",
        "docker",
        "gelidum",
        "idna",
        "jmespath",
        "networkx",
        "numpy",
        "Parsley",
        "pydantic",
        "Pygments",
        "python-dateutil",
        "python-json-logger",
        "requests",
        "rich",
        "s3transfer",
        "six",
        "sortedcontainers",
        "typing-extensions",
        "urllib3",
        "watchdog",
        "websocket-client",
    ],
    python_requires='>=3.7'
)
